// Database types placeholder - will be generated by Supabase CLI
// For now, re-export entity types for convenience
export type {
  Profile,
  Brand,
  QueryTemplate,
  LLMResponse,
  VisibilityScore,
  Recommendation,
  Subscription,
  AuditLead,
} from '@/types';
